@ECHO OFF
echo Cleaning working directory...
del ImageTweak.xpi >nul 2>nul
echo Creating XPI...
".\build\bin\7-Zip\7za" a -xr!bitcons -xr!newicon -x!skin\favicon.ico -x!.git* -x!build.bat -x!desktop.ini -mx9 -tzip ImageTweak.xpi * >nul 2>nul
echo All done!